version: "3.8"

networks:
  hackathon:
    driver: bridge

volumes:
  esdata:
    driver: local

services:
  # The data storage
  es:
    # NOTE: Need to run this command in the host to start ES:
    #
    # sudo sysctl -w vm.max_map_count=262144
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.5.1'
    container_name: es
    networks:
      - hackathon
    ports:
      - '9200:9200'
    environment:
      - node.name=es
      - cluster.name=alamod-es
      - cluster.initial_master_nodes=es
      # NOTE: The -Xms and -Xmx values must be same for ES
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # The modsec/nginx firewall
  waf:
    image: 'dregis.strangeloop.net/hackathon-2020/wafmod:1.0.0'
    container_name: waf
    networks:
      - hackathon
    ports:
      - "8443:443"
      - "8000:80"
    depends_on:
      - be

  # Our backend server
  be:
    image: "dregis.strangeloop.net/hackathon-2020/server:0.1"
    container_name: be
    networks:
      - hackathon
    ports:
      - '8088:80'
    environment:
      ES_HOSTNAME: es
      ES_PORT: 9200
      ES_CLUSTER: alamod-es
    depends_on:
      - es

